version: '3.8'
services:
  db:
    image: mysql
    container_name: ecommerceapi-db
    restart: always
    environment:
      MYSQL_DATABASE: 'ecommerce'
      MYSQL_PASSWORD: 'ChiNghia08062004'
    ports:
      - '3307:3306'
    networks:
      - blogapi-network
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=ChiNghia08062004 --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    volumes:
      - ./data:/docker-entrypoint-initdb.d
  application:
    container_name: ecommerceapi-application
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3307:8080"
    networks:
      - ecommerceapi-network
    depends_on:
      - "db"
networks:
  ecommerceapi-network:
    name: ecommerceapi-network
    driver: bridge