version: '3.8'

services:
  mysql:
    image: mysql:8.1
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "ChiNghia08062004"
      MYSQL_DATABASE: "classicmodels"
      MYSQL_USER: "root"
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
