spring:
  datasource:
    url: jdbc:mysql://localhost:3307/ecommerce?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

app:
  apiPrefix: localhost:8080/api
  jwtSecret: secret123
  jwtExpirationInMs: 3600000

cors:
  allowedOrings: '*'